kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dwpweb
  namespace: departmentworkpensions
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dwpweb
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: dwpweb
        image: mycluster.icp:8500/dwp/dwpweb:latest
        env:
          - name: VERSION
            value: "1"
        ports:
        - containerPort: 9080
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
      imagePullSecrets:
        - name: myregistrykey